---
- name: PostgreSQL | Add db in PostgreSQL
  community.general.postgresql_db:
    name: "{{ item.db }}"
    encoding: '{{ item.encoding | default("UNICODE") }}'
    owner: "{{ item.user | default(postgresql_users.0.name) }}"
    port: "{{ postgresql_port }}"
  with_items: "{{ postgresql_dbs }}"

- name: PostgreSQL | Added extensions to a database
  community.general.postgresql_ext:
    name: "{{ item.1 }}"
    db: "{{ item.0.db }}"
    port: "{{ postgresql_port }}"
  with_subelements:
    - "{{ postgresql_dbs }}"
    - ext
    - flags:
      skip_missing: True

- name: PostgreSQL | Added schemas to a database
  community.general.postgresql_schema:
    name: "{{ item.1 }}"
    database: "{{ item.0.db }}"
    owner: "{{ item.0.user | default(postgresql_users.0.name)  }}"
  with_subelements:
    - "{{ postgresql_dbs }}"
    - schema
    - flags:
      skip_missing: True

- name: PostgreSQL | Add privs in PostgreSQL
  community.general.postgresql_privs:
    db: postgres
    type: database
    privs: ALL
    obj: "{{ item.db }}"
    role: "{{ item.user | default(postgresql_users.0.name) }}"
    port: "{{ postgresql_port }}"
  with_items: "{{ postgresql_dbs }}"
  ignore_errors: true