---
- name: "restart postgresql"
  ansible.builtin.service:
    name: postgresql
    state: restarted
    enabled: yes

- name: "reload postgresql"
  ansible.builtin.service:
    name: postgresql
    state: reloaded
    enabled: yes

- name: "start postgresql"
  ansible.builtin.service:
    name: postgresql
    state: started
    enabled: yes

