---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: ubuntu
    image: geerlingguy/docker-ubuntu2204-ansible
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    priviledged: true
    capabilities:
      - SYS_ADMIN
    command: "/sbin/init"
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
lint:
  name: yamllint